### ISSUE TITLE
npm run build fails after the latest update

### ISSUE THREAD

**Issue by anshumanv** [TeamWertarbyte/material-ui-password-field#21]
I'm using this package in a project and that runs autodeployment using travis to gh-pages branch, just recently after these updates the project fails to compile as shown below, what do I do to get things right? Add @material-ui/core as a dependency to the project? Any help would be appreciated. Thanks :smile: 

![image](https://user-images.githubusercontent.com/21009455/40404652-94ef6228-5e76-11e8-9a0c-124abb427b5b.png)

**Comment by leMaik** [comment]
Please read [the changelog](https://github.com/TeamWertarbyte/material-ui-password-field/releases/tag/v2.0.0).

It was a major version bump because there were **breaking changes**, i.e. Material-UI was updated to version 1.0.0. If you're using an older version, don't update to v2.0.0 and you'll be fine. You should update to Material-UI 1.0.0 though, but that requires a bit of work.

**Comment by anshumanv** [comment]
@leMaik Okay thanks.
